### ISSUE TITLE
Hey, just a quick request

### ISSUE THREAD

**Issue by GreenBayRules** [Torotv/Torotv#2]
Can you please delete all of your forks of my repository? There is no need for them unless you are making a pull request, which you are not. Please delete all the repositories that are forked from me, thanks :D

**Comment by Torotv** [comment]
I Can't! I LIke Have Over 90 Resporitses! ANd I Will Make Pull requests!

**Comment by GreenBayRules** [comment]
I'll send you the links of all your repositories that are forked from me. then you can delete them

**Comment by Torotv** [comment]
Hey! I wnated to Make A Code That COnnects to The isonline server and on  interent explorar you can put the code and find out their stauts. SO, Can I have the link aof the isonline server and can you help me?
